VALID_USER_DATA = [
        {'username': 'leahvelleman',
         'email': 'leahvelleman@gmail.com',
         'password': 'zooblefart'},
        {'username': 'accéntedchãraçtérs',
         'email': 'fancyletters@foo.com',
         'password': '2r039fjaio'},
        {'username': 'someoneelse',
         'email': 'someone.else@gmail.com',
         'password': 'squeedleblorf'},
        {'username': 'FredNull',
         'email': 'fnull@example.com',
         'password': 'wo239u3hofwasf'},
        {'username': '도윤김',
         'email': 'doyeonkim@gmail.com',
         'password': '2398rhfeoriaselfjwe'},
        {'username': 'ExtendedUnicodePassword',
         'email': 'somuchunicode@gmail.com',
         'password': '表ポあA鷗ŒéＢ逍Üßªąñ丂㐀𠀀'},
         ]

INVALID_USER_DATA = [
        {'username': '',
         'email': 'no.username@gmail.com',
         'password': 'zooblefart'},
        {'username': '💕 💞 💓 💗 💖',
         'email': 'shmoopybutt@gmail.com',
         'password': '28hfiaslawe'},
        {'username': 'No Email',
         'email': None,
         'password': 'squeedleblorf'},
        {'username': 123,
         'email': 'username.is.the.wrong.type@hotmail.com',
         'password': '2aeaica'},
        {'username': 'Extra fields',
         'email': 'foo@foo.com',
         'useless': 'this is bad',
         'password': 'squeedleblorf'},
         ]
