"""empty message

Revision ID: 1fb1589943a1
Revises: 78f81bf1f6ec
Create Date: 2020-04-10 20:23:45.688096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb1589943a1'
down_revision = '78f81bf1f6ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_username', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_username', 'users', ['username'])
    # ### end Alembic commands ###
