"""Add unique constraint to username

Revision ID: 2f6b596bd0e5
Revises: 53ace6cbdef4
Create Date: 2020-04-10 15:15:52.119340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6b596bd0e5'
down_revision = '53ace6cbdef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
