"""empty message

Revision ID: 3793bc22c85a
Revises: b59fd0679b90
Create Date: 2020-04-10 20:51:46.468377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3793bc22c85a'
down_revision = 'b59fd0679b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sibling_order', 'items', type_='unique')
    op.create_unique_constraint('sibling_order', 'items', ['order', 'parent_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sibling_order', 'items', type_='unique')
    op.create_unique_constraint('sibling_order', 'items', ['order'])
    # ### end Alembic commands ###
