"""Add named uniqueness constraint for username

Revision ID: 78f81bf1f6ec
Revises: 2f6b596bd0e5
Create Date: 2020-04-10 15:30:23.126322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f81bf1f6ec'
down_revision = '2f6b596bd0e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_username', 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_username', 'users', type_='unique')
    # ### end Alembic commands ###
