"""empty message

Revision ID: b59fd0679b90
Revises: e841b2d84b74
Create Date: 2020-04-10 20:51:06.753261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59fd0679b90'
down_revision = 'e841b2d84b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sibling_order', 'items', type_='unique')
    op.create_unique_constraint('sibling_order', 'items', ['order'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sibling_order', 'items', type_='unique')
    op.create_unique_constraint('sibling_order', 'items', ['order', 'parent_id'])
    # ### end Alembic commands ###
